In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import sklearn as skl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings # current version of seaborn generates a bunch of warnings that will be ignore
warnings.filterwarnings('ignore')

In [3]:
train = pd.read_csv("train.csv")
test  = pd.read_csv("test.csv")

In [4]:
train.drop(['PassengerId', 'Cabin', 'Name', 'Fare', 'Ticket'], axis=1, inplace=True)
test.drop(['Cabin', 'Name', 'Fare', 'Ticket'], axis=1, inplace=True)

In [5]:
train.dropna(subset=['Embarked'], how='any', inplace=True)
test.dropna(subset=['Embarked'], how='any', inplace=True)

In [6]:
train.Age=train.Age.fillna(value=train.Age.mean())
test.Age=test.Age.fillna(value=train.Age.mean())

In [7]:
Xtrain = train.drop(['Survived'], axis=1)
ytrain = train['Survived']

Xtest = test.drop("PassengerId", axis=1)
#ytest

In [8]:
genders = {"male": 0, "female": 1}
Xtrain['Sex'] = train['Sex'].map(genders)
Xtest['Sex'] = test['Sex'].map(genders)

In [9]:
ports = {"S": 0, "C": 1, "Q": 2}
Xtrain['Embarked'] = train['Embarked'].map(ports)
Xtest['Embarked'] = test['Embarked'].map(ports)

In [1]:
#Xtrain.head()

# Decomposition
* PCA

In [11]:
from sklearn.decomposition import PCA

from mpl_toolkits import mplot3d

In [39]:
pca = PCA(n_components=3)
# X_train = train.drop('Survived', axis=1)
#Xtrain_pca = pca.fit_transform(train.drop('Survived', axis=1))
Xtrain_pca = pca.fit_transform(Xtrain)

In [13]:
Xtrain_pca

array([[-7.65713958,  0.06313449, -0.65987168],
       [ 8.37455169,  0.48429713,  1.00765383],
       [-3.64250917, -0.66263378, -0.45151249],
       ...,
       [-0.04438514,  1.19354951, -0.29780069],
       [-3.59638295, -0.75366609,  1.2203347 ],
       [ 2.35873264, -0.71694322, -0.90224093]])

In [14]:
len(Xtrain_pca)

889

# 3. MODEL

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score

from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# PCA

* PCA 1 - using accuracy_score

In [40]:
# make predictions
LR = LogisticRegression()
LR.fit(Xtrain_pca, ytrain)

newdata_transformed = pca.transform(Xtrain)
predictions = LR.predict(newdata_transformed)

print("Accuracy:", accuracy_score(predictions, ytrain))
#print(confusion_matrix(predictions, y))
#print(classification_report(predictions, y))

Accuracy: 0.7154105736782902


In [17]:
predictions = LR.predict(pca.transform(Xtest))

In [18]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [19]:
len(predictions)

418

* PCA 2 - Using cross_val_score ????????????????????????

In [62]:
# make predictions
LR = LogisticRegression()
LR.fit(Xtrain_pca, ytrain)

newdata_transformed = pca.transform(Xtrain)
predictions = LR.predict(newdata_transformed)
#predictions = LR.predict(pca.transform(Xtrain))

cross_val_score(LR, Xtrain, ytrain).mean() #, scoring = 'accuracy'
#cross_val_score(LR, predictions, ytrain.to_numpy(), scoring = 'accuracy').mean()

0.7930240846907514

In [52]:
#predictions

In [60]:
#type(predictions)

In [56]:
#len(predictions)

In [48]:
#ytrain

In [58]:
#type(ytrain)

In [64]:
#ytrain.to_numpy()

In [47]:
#len(ytrain)

In [21]:
predictions = LR.predict(pca.transform(Xtest))

In [22]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [23]:
len(predictions)

418

# PCA Pipelining

In [24]:
from sklearn.pipeline import Pipeline

* Pipelining 1 - Using accuracy_score

In [25]:
pipe = Pipeline( [ ('pca', PCA(n_components=3)), ('LR', LogisticRegression()) ] )
pipe.fit(Xtrain, ytrain)

predictions = pipe.predict(Xtrain)

accuracy_score(predictions, ytrain)
#cross_val_score(pipe, Xtrain, ytrain).mean()

0.7154105736782902

In [26]:
predictions = pipe.predict(Xtest)

In [27]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [28]:
len(predictions)

418

* Pipelining 2 - Using cross_val_score

In [29]:
pipe = Pipeline( [ ('pca', PCA(n_components=3)), ('LR', LogisticRegression()) ] )
pipe.fit(Xtrain, ytrain)

predictions = pipe.predict(Xtrain)

cross_val_score(pipe, Xtrain, ytrain).mean()
#cross_val_score(pipe, predictions, ytrain).mean()

0.714335547668881

In [30]:
predictions = pipe.predict(Xtest)

In [31]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [32]:
len(predictions)

418